// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -118363328;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'mnn_llm_frb',
    ioDirectory: 'rust/mnn_llm/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiMnnLlmApplyChatTemplate({required MnnLlm that, required String messagesJson});

  Future<String> crateApiMnnLlmChat({required MnnLlm that, required String messagesJson});

  MnnLlm crateApiMnnLlmCreate({required String configPath});

  Future<String> crateApiMnnLlmDetokenize({required MnnLlm that, required List<int> tokens});

  Future<void> crateApiMnnLlmDispose({required MnnLlm that});

  String crateApiMnnLlmDumpConfig({required MnnLlm that});

  Future<void> crateApiMnnLlmEraseHistory({required MnnLlm that, required BigInt begin, required BigInt end});

  Future<String> crateApiMnnLlmGenerate({required MnnLlm that, required String prompt});

  Stream<String> crateApiMnnLlmGenerateStream({required MnnLlm that, required String prompt});

  Future<ContextInfo?> crateApiMnnLlmGetContextInfo({required MnnLlm that});

  Future<String> crateApiMnnLlmGetGeneratedString({required MnnLlm that});

  Future<BigInt> crateApiMnnLlmGetHistoryLength({required MnnLlm that});

  Future<Int32List> crateApiMnnLlmGetHistoryTokens({required MnnLlm that});

  Future<Int32List> crateApiMnnLlmGetOutputTokens({required MnnLlm that});

  Future<bool> crateApiMnnLlmIsStopped({required MnnLlm that});

  Future<bool> crateApiMnnLlmLoad({required MnnLlm that});

  Future<void> crateApiMnnLlmReset({required MnnLlm that});

  Future<void> crateApiMnnLlmSetConfig({required MnnLlm that, required String configJson});

  Future<void> crateApiMnnLlmSetThinking({required MnnLlm that, required bool enabled});

  Future<Int32List> crateApiMnnLlmTokenize({required MnnLlm that, required String text});

  Future<void> crateApiMnnLlmTune({required MnnLlm that});

  Future<String> crateApiMnnLlmVisionGenerate({
    required MnnLlm that,
    required String prompt,
    required String imagePaths,
    int? width,
    int? height,
  });

  Stream<String> crateApiMnnLlmVisionGenerateStream({
    required MnnLlm that,
    required String prompt,
    required String imagePaths,
    int? width,
    int? height,
  });

  Future<void> crateApiInitApp();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_MnnLlm;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_MnnLlm;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MnnLlmPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiMnnLlmApplyChatTemplate({required MnnLlm that, required String messagesJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_String(messagesJson);
          return wire.wire__crate__api__MnnLlm_apply_chat_template(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmApplyChatTemplateConstMeta,
        argValues: [that, messagesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmApplyChatTemplateConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_apply_chat_template", argNames: ["that", "messagesJson"]);

  @override
  Future<String> crateApiMnnLlmChat({required MnnLlm that, required String messagesJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_String(messagesJson);
          return wire.wire__crate__api__MnnLlm_chat(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmChatConstMeta,
        argValues: [that, messagesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmChatConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_chat", argNames: ["that", "messagesJson"]);

  @override
  MnnLlm crateApiMnnLlmCreate({required String configPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(configPath);
          return wire.wire__crate__api__MnnLlm_create(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiMnnLlmCreateConstMeta,
        argValues: [configPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmCreateConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_create", argNames: ["configPath"]);

  @override
  Future<String> crateApiMnnLlmDetokenize({required MnnLlm that, required List<int> tokens}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_list_prim_i_32_loose(tokens);
          return wire.wire__crate__api__MnnLlm_detokenize(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmDetokenizeConstMeta,
        argValues: [that, tokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmDetokenizeConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_detokenize", argNames: ["that", "tokens"]);

  @override
  Future<void> crateApiMnnLlmDispose({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_dispose(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmDisposeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmDisposeConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_dispose", argNames: ["that"]);

  @override
  String crateApiMnnLlmDumpConfig({required MnnLlm that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_dump_config(arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: null),
        constMeta: kCrateApiMnnLlmDumpConfigConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmDumpConfigConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_dump_config", argNames: ["that"]);

  @override
  Future<void> crateApiMnnLlmEraseHistory({required MnnLlm that, required BigInt begin, required BigInt end}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_usize(begin);
          var arg2 = cst_encode_usize(end);
          return wire.wire__crate__api__MnnLlm_erase_history(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmEraseHistoryConstMeta,
        argValues: [that, begin, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmEraseHistoryConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_erase_history", argNames: ["that", "begin", "end"]);

  @override
  Future<String> crateApiMnnLlmGenerate({required MnnLlm that, required String prompt}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_String(prompt);
          return wire.wire__crate__api__MnnLlm_generate(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmGenerateConstMeta,
        argValues: [that, prompt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmGenerateConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_generate", argNames: ["that", "prompt"]);

  @override
  Stream<String> crateApiMnnLlmGenerateStream({required MnnLlm that, required String prompt}) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
            var arg1 = cst_encode_String(prompt);
            var arg2 = cst_encode_StreamSink_String_Dco(sink);
            return wire.wire__crate__api__MnnLlm_generate_stream(port_, arg0, arg1, arg2);
          },
          codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
          constMeta: kCrateApiMnnLlmGenerateStreamConstMeta,
          argValues: [that, prompt, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMnnLlmGenerateStreamConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_generate_stream", argNames: ["that", "prompt", "sink"]);

  @override
  Future<ContextInfo?> crateApiMnnLlmGetContextInfo({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_get_context_info(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_opt_box_autoadd_context_info, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmGetContextInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmGetContextInfoConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_get_context_info", argNames: ["that"]);

  @override
  Future<String> crateApiMnnLlmGetGeneratedString({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_get_generated_string(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmGetGeneratedStringConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmGetGeneratedStringConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_get_generated_string", argNames: ["that"]);

  @override
  Future<BigInt> crateApiMnnLlmGetHistoryLength({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_get_history_length(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_usize, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmGetHistoryLengthConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmGetHistoryLengthConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_get_history_length", argNames: ["that"]);

  @override
  Future<Int32List> crateApiMnnLlmGetHistoryTokens({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_get_history_tokens(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_list_prim_i_32_strict, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmGetHistoryTokensConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmGetHistoryTokensConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_get_history_tokens", argNames: ["that"]);

  @override
  Future<Int32List> crateApiMnnLlmGetOutputTokens({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_get_output_tokens(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_list_prim_i_32_strict, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmGetOutputTokensConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmGetOutputTokensConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_get_output_tokens", argNames: ["that"]);

  @override
  Future<bool> crateApiMnnLlmIsStopped({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_is_stopped(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_bool, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmIsStoppedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmIsStoppedConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_is_stopped", argNames: ["that"]);

  @override
  Future<bool> crateApiMnnLlmLoad({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_load(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_bool, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmLoadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmLoadConstMeta => const TaskConstMeta(debugName: "MnnLlm_load", argNames: ["that"]);

  @override
  Future<void> crateApiMnnLlmReset({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_reset(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmResetConstMeta => const TaskConstMeta(debugName: "MnnLlm_reset", argNames: ["that"]);

  @override
  Future<void> crateApiMnnLlmSetConfig({required MnnLlm that, required String configJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_String(configJson);
          return wire.wire__crate__api__MnnLlm_set_config(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmSetConfigConstMeta,
        argValues: [that, configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmSetConfigConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_set_config", argNames: ["that", "configJson"]);

  @override
  Future<void> crateApiMnnLlmSetThinking({required MnnLlm that, required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_bool(enabled);
          return wire.wire__crate__api__MnnLlm_set_thinking(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmSetThinkingConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmSetThinkingConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_set_thinking", argNames: ["that", "enabled"]);

  @override
  Future<Int32List> crateApiMnnLlmTokenize({required MnnLlm that, required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_String(text);
          return wire.wire__crate__api__MnnLlm_tokenize(port_, arg0, arg1);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_list_prim_i_32_strict, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmTokenizeConstMeta,
        argValues: [that, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmTokenizeConstMeta =>
      const TaskConstMeta(debugName: "MnnLlm_tokenize", argNames: ["that", "text"]);

  @override
  Future<void> crateApiMnnLlmTune({required MnnLlm that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          return wire.wire__crate__api__MnnLlm_tune(port_, arg0);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmTuneConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmTuneConstMeta => const TaskConstMeta(debugName: "MnnLlm_tune", argNames: ["that"]);

  @override
  Future<String> crateApiMnnLlmVisionGenerate({
    required MnnLlm that,
    required String prompt,
    required String imagePaths,
    int? width,
    int? height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
          var arg1 = cst_encode_String(prompt);
          var arg2 = cst_encode_String(imagePaths);
          var arg3 = cst_encode_opt_box_autoadd_i_32(width);
          var arg4 = cst_encode_opt_box_autoadd_i_32(height);
          return wire.wire__crate__api__MnnLlm_vision_generate(port_, arg0, arg1, arg2, arg3, arg4);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_String),
        constMeta: kCrateApiMnnLlmVisionGenerateConstMeta,
        argValues: [that, prompt, imagePaths, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMnnLlmVisionGenerateConstMeta => const TaskConstMeta(
    debugName: "MnnLlm_vision_generate",
    argNames: ["that", "prompt", "imagePaths", "width", "height"],
  );

  @override
  Stream<String> crateApiMnnLlmVisionGenerateStream({
    required MnnLlm that,
    required String prompt,
    required String imagePaths,
    int? width,
    int? height,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(that);
            var arg1 = cst_encode_String(prompt);
            var arg2 = cst_encode_String(imagePaths);
            var arg3 = cst_encode_opt_box_autoadd_i_32(width);
            var arg4 = cst_encode_opt_box_autoadd_i_32(height);
            var arg5 = cst_encode_StreamSink_String_Dco(sink);
            return wire.wire__crate__api__MnnLlm_vision_generate_stream(port_, arg0, arg1, arg2, arg3, arg4, arg5);
          },
          codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: dco_decode_String),
          constMeta: kCrateApiMnnLlmVisionGenerateStreamConstMeta,
          argValues: [that, prompt, imagePaths, width, height, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMnnLlmVisionGenerateStreamConstMeta => const TaskConstMeta(
    debugName: "MnnLlm_vision_generate_stream",
    argNames: ["that", "prompt", "imagePaths", "width", "height", "sink"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__init_app(port_);
        },
        codec: DcoCodec(decodeSuccessData: dco_decode_unit, decodeErrorData: null),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_MnnLlm =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_MnnLlm =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MnnLlm dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MnnLlmImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MnnLlm dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MnnLlmImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MnnLlm dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MnnLlmImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Dco(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ContextInfo dco_decode_box_autoadd_context_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_context_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ContextInfo dco_decode_context_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ContextInfo(
      promptTokens: dco_decode_i_32(arr[0]),
      decodeTokens: dco_decode_i_32(arr[1]),
      promptUs: dco_decode_i_64(arr[2]),
      decodeUs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ContextInfo? dco_decode_opt_box_autoadd_context_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_context_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MnnLlm sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MnnLlmImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MnnLlm sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MnnLlmImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MnnLlm sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MnnLlmImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Dco(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ContextInfo sse_decode_box_autoadd_context_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_context_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  ContextInfo sse_decode_context_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_promptTokens = sse_decode_i_32(deserializer);
    var var_decodeTokens = sse_decode_i_32(deserializer);
    var var_promptUs = sse_decode_i_64(deserializer);
    var var_decodeUs = sse_decode_i_64(deserializer);
    return ContextInfo(
      promptTokens: var_promptTokens,
      decodeTokens: var_decodeTokens,
      promptUs: var_promptUs,
      decodeUs: var_decodeUs,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ContextInfo? sse_decode_opt_box_autoadd_context_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_context_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MnnLlmImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MnnLlmImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MnnLlmImpl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as MnnLlmImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as MnnLlmImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as MnnLlmImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Dco(RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_AnyhowException),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_context_info(ContextInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_context_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_context_info(ContextInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.promptTokens, serializer);
    sse_encode_i_32(self.decodeTokens, serializer);
    sse_encode_i_64(self.promptUs, serializer);
    sse_encode_i_64(self.decodeUs, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_i_32_loose(List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self is Int32List ? self : Int32List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_i_32_strict(Int32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_context_info(ContextInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_context_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class MnnLlmImpl extends RustOpaque implements MnnLlm {
  // Not to be used by end users
  MnnLlmImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MnnLlmImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_MnnLlm,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_MnnLlm,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_MnnLlmPtr,
  );

  /// Apply chat template to messages
  ///
  /// # Arguments
  /// * `messages_json` - JSON array of messages: `[{"role":"user","content":"..."}]`
  ///
  /// # Returns
  /// Formatted prompt string with chat template applied
  Future<String> applyChatTemplate({required String messagesJson}) =>
      RustLib.instance.api.crateApiMnnLlmApplyChatTemplate(that: this, messagesJson: messagesJson);

  /// Generate response using chat messages format (non-streaming)
  ///
  /// # Arguments
  /// * `messages_json` - JSON object: `{"messages":[{"role":"user","content":"..."}]}`
  Future<String> chat({required String messagesJson}) =>
      RustLib.instance.api.crateApiMnnLlmChat(that: this, messagesJson: messagesJson);

  /// Decode tokens to text
  Future<String> detokenize({required List<int> tokens}) =>
      RustLib.instance.api.crateApiMnnLlmDetokenize(that: this, tokens: tokens);

  /// Explicitly release the model and free all resources
  ///
  /// Call this before creating a new model to ensure clean memory state.
  /// After calling dispose, this instance should not be used.
  Future<void> dispose() => RustLib.instance.api.crateApiMnnLlmDispose(that: this);

  /// Get the model's current configuration as JSON
  String dumpConfig() => RustLib.instance.api.crateApiMnnLlmDumpConfig(that: this);

  /// Erase history tokens in a range
  Future<void> eraseHistory({required BigInt begin, required BigInt end}) =>
      RustLib.instance.api.crateApiMnnLlmEraseHistory(that: this, begin: begin, end: end);

  /// Generate a complete response (non-streaming)
  ///
  /// Use this when you need the full response at once.
  Future<String> generate({required String prompt}) =>
      RustLib.instance.api.crateApiMnnLlmGenerate(that: this, prompt: prompt);

  /// Generate a streaming response
  ///
  /// Streams text chunks as they're generated.
  Stream<String> generateStream({required String prompt}) =>
      RustLib.instance.api.crateApiMnnLlmGenerateStream(that: this, prompt: prompt);

  /// Get context information (performance metrics)
  Future<ContextInfo?> getContextInfo() => RustLib.instance.api.crateApiMnnLlmGetContextInfo(that: this);

  /// Get generated string from context
  Future<String> getGeneratedString() => RustLib.instance.api.crateApiMnnLlmGetGeneratedString(that: this);

  /// Get current history length (number of tokens)
  Future<BigInt> getHistoryLength() => RustLib.instance.api.crateApiMnnLlmGetHistoryLength(that: this);

  /// Get history tokens
  Future<Int32List> getHistoryTokens() => RustLib.instance.api.crateApiMnnLlmGetHistoryTokens(that: this);

  /// Get output tokens from last generation
  Future<Int32List> getOutputTokens() => RustLib.instance.api.crateApiMnnLlmGetOutputTokens(that: this);

  /// Check if generation has stopped
  Future<bool> isStopped() => RustLib.instance.api.crateApiMnnLlmIsStopped(that: this);

  /// Load the model into memory
  ///
  /// Must be called before generating responses.
  Future<bool> load() => RustLib.instance.api.crateApiMnnLlmLoad(that: this);

  /// Reset conversation history
  ///
  /// Call this to start a new conversation.
  Future<void> reset() => RustLib.instance.api.crateApiMnnLlmReset(that: this);

  /// Set configuration options (JSON format)
  ///
  /// Call before load() to set options like use_mmap, tmp_path, backend, etc.
  ///
  /// # Arguments
  /// * `config_json` - JSON string with configuration options
  Future<void> setConfig({required String configJson}) =>
      RustLib.instance.api.crateApiMnnLlmSetConfig(that: this, configJson: configJson);

  /// Enable or disable thinking mode for reasoning models
  Future<void> setThinking({required bool enabled}) =>
      RustLib.instance.api.crateApiMnnLlmSetThinking(that: this, enabled: enabled);

  /// Encode text to tokens
  Future<Int32List> tokenize({required String text}) =>
      RustLib.instance.api.crateApiMnnLlmTokenize(that: this, text: text);

  /// Tune the model for optimal performance
  ///
  /// Call this after loading for best inference speed.
  Future<void> tune() => RustLib.instance.api.crateApiMnnLlmTune(that: this);

  /// Vision: Generate complete response with image(s) (non-streaming)
  Future<String> visionGenerate({required String prompt, required String imagePaths, int? width, int? height}) =>
      RustLib.instance.api.crateApiMnnLlmVisionGenerate(
        that: this,
        prompt: prompt,
        imagePaths: imagePaths,
        width: width,
        height: height,
      );

  /// Vision: Generate streaming response with image(s)
  ///
  /// # Arguments
  /// * `prompt` - Text prompt
  /// * `image_paths` - Comma-separated image paths or URLs
  /// * `width` - Optional image width (0 for auto)
  /// * `height` - Optional image height (0 for auto)
  /// * `sink` - StreamSink to receive text chunks
  Stream<String> visionGenerateStream({required String prompt, required String imagePaths, int? width, int? height}) =>
      RustLib.instance.api.crateApiMnnLlmVisionGenerateStream(
        that: this,
        prompt: prompt,
        imagePaths: imagePaths,
        width: width,
        height: height,
      );
}
