// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MnnLlmPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  MnnLlm dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw);

  @protected
  MnnLlm dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw);

  @protected
  MnnLlm dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContextInfo dco_decode_box_autoadd_context_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  ContextInfo dco_decode_context_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  ContextInfo? dco_decode_opt_box_autoadd_context_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  MnnLlm sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    SseDeserializer deserializer,
  );

  @protected
  MnnLlm sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    SseDeserializer deserializer,
  );

  @protected
  MnnLlm sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Dco(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContextInfo sse_decode_box_autoadd_context_info(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ContextInfo sse_decode_context_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ContextInfo? sse_decode_opt_box_autoadd_context_info(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_StreamSink_String_Dco(RustStreamSink<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_AnyhowException),
      ),
    );
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_context_info(ContextInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_context_info(raw);
  }

  @protected
  int cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw);
  }

  @protected
  JSAny cst_encode_context_info(ContextInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.promptTokens),
      cst_encode_i_32(raw.decodeTokens),
      cst_encode_i_64(raw.promptUs),
      cst_encode_i_64(raw.decodeUs),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_prim_i_32_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_i_32_strict(Int32List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_context_info(ContextInfo? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_context_info(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Dco(RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_context_info(ContextInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_context_info(ContextInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_context_info(ContextInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__MnnLlm_apply_chat_template(NativePortType port_, int that, String messages_json) =>
      wasmModule.wire__crate__api__MnnLlm_apply_chat_template(port_, that, messages_json);

  void wire__crate__api__MnnLlm_chat(NativePortType port_, int that, String messages_json) =>
      wasmModule.wire__crate__api__MnnLlm_chat(port_, that, messages_json);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */ wire__crate__api__MnnLlm_create(
    String config_path,
  ) => wasmModule.wire__crate__api__MnnLlm_create(config_path);

  void wire__crate__api__MnnLlm_detokenize(NativePortType port_, int that, JSAny tokens) =>
      wasmModule.wire__crate__api__MnnLlm_detokenize(port_, that, tokens);

  void wire__crate__api__MnnLlm_dispose(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_dispose(port_, that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */ wire__crate__api__MnnLlm_dump_config(
    int that,
  ) => wasmModule.wire__crate__api__MnnLlm_dump_config(that);

  void wire__crate__api__MnnLlm_erase_history(NativePortType port_, int that, JSAny begin, JSAny end) =>
      wasmModule.wire__crate__api__MnnLlm_erase_history(port_, that, begin, end);

  void wire__crate__api__MnnLlm_generate(NativePortType port_, int that, String prompt) =>
      wasmModule.wire__crate__api__MnnLlm_generate(port_, that, prompt);

  void wire__crate__api__MnnLlm_generate_stream(NativePortType port_, int that, String prompt, String sink) =>
      wasmModule.wire__crate__api__MnnLlm_generate_stream(port_, that, prompt, sink);

  void wire__crate__api__MnnLlm_get_context_info(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_get_context_info(port_, that);

  void wire__crate__api__MnnLlm_get_generated_string(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_get_generated_string(port_, that);

  void wire__crate__api__MnnLlm_get_history_length(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_get_history_length(port_, that);

  void wire__crate__api__MnnLlm_get_history_tokens(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_get_history_tokens(port_, that);

  void wire__crate__api__MnnLlm_get_output_tokens(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_get_output_tokens(port_, that);

  void wire__crate__api__MnnLlm_is_stopped(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_is_stopped(port_, that);

  void wire__crate__api__MnnLlm_load(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_load(port_, that);

  void wire__crate__api__MnnLlm_reset(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_reset(port_, that);

  void wire__crate__api__MnnLlm_set_config(NativePortType port_, int that, String config_json) =>
      wasmModule.wire__crate__api__MnnLlm_set_config(port_, that, config_json);

  void wire__crate__api__MnnLlm_set_thinking(NativePortType port_, int that, bool enabled) =>
      wasmModule.wire__crate__api__MnnLlm_set_thinking(port_, that, enabled);

  void wire__crate__api__MnnLlm_tokenize(NativePortType port_, int that, String text) =>
      wasmModule.wire__crate__api__MnnLlm_tokenize(port_, that, text);

  void wire__crate__api__MnnLlm_tune(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__MnnLlm_tune(port_, that);

  void wire__crate__api__MnnLlm_vision_generate(
    NativePortType port_,
    int that,
    String prompt,
    String image_paths,
    int? width,
    int? height,
  ) => wasmModule.wire__crate__api__MnnLlm_vision_generate(port_, that, prompt, image_paths, width, height);

  void wire__crate__api__MnnLlm_vision_generate_stream(
    NativePortType port_,
    int that,
    String prompt,
    String image_paths,
    int? width,
    int? height,
    String sink,
  ) =>
      wasmModule.wire__crate__api__MnnLlm_vision_generate_stream(port_, that, prompt, image_paths, width, height, sink);

  void wire__crate__api__init_app(NativePortType port_) => wasmModule.wire__crate__api__init_app(port_);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
        ptr,
      );

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__MnnLlm_apply_chat_template(NativePortType port_, int that, String messages_json);

  external void wire__crate__api__MnnLlm_chat(NativePortType port_, int that, String messages_json);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */ wire__crate__api__MnnLlm_create(
    String config_path,
  );

  external void wire__crate__api__MnnLlm_detokenize(NativePortType port_, int that, JSAny tokens);

  external void wire__crate__api__MnnLlm_dispose(NativePortType port_, int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */ wire__crate__api__MnnLlm_dump_config(
    int that,
  );

  external void wire__crate__api__MnnLlm_erase_history(NativePortType port_, int that, JSAny begin, JSAny end);

  external void wire__crate__api__MnnLlm_generate(NativePortType port_, int that, String prompt);

  external void wire__crate__api__MnnLlm_generate_stream(NativePortType port_, int that, String prompt, String sink);

  external void wire__crate__api__MnnLlm_get_context_info(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_get_generated_string(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_get_history_length(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_get_history_tokens(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_get_output_tokens(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_is_stopped(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_load(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_reset(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_set_config(NativePortType port_, int that, String config_json);

  external void wire__crate__api__MnnLlm_set_thinking(NativePortType port_, int that, bool enabled);

  external void wire__crate__api__MnnLlm_tokenize(NativePortType port_, int that, String text);

  external void wire__crate__api__MnnLlm_tune(NativePortType port_, int that);

  external void wire__crate__api__MnnLlm_vision_generate(
    NativePortType port_,
    int that,
    String prompt,
    String image_paths,
    int? width,
    int? height,
  );

  external void wire__crate__api__MnnLlm_vision_generate_stream(
    NativePortType port_,
    int that,
    String prompt,
    String image_paths,
    int? width,
    int? height,
    String sink,
  );

  external void wire__crate__api__init_app(NativePortType port_);

  external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    int ptr,
  );

  external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    int ptr,
  );
}
