// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MnnLlmPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlmPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  MnnLlm dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw);

  @protected
  MnnLlm dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw);

  @protected
  MnnLlm dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContextInfo dco_decode_box_autoadd_context_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  ContextInfo dco_decode_context_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  ContextInfo? dco_decode_opt_box_autoadd_context_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  MnnLlm sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    SseDeserializer deserializer,
  );

  @protected
  MnnLlm sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    SseDeserializer deserializer,
  );

  @protected
  MnnLlm sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Dco(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContextInfo sse_decode_box_autoadd_context_info(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ContextInfo sse_decode_context_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ContextInfo? sse_decode_opt_box_autoadd_context_info(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_StreamSink_String_Dco(RustStreamSink<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(decodeSuccessData: dco_decode_String, decodeErrorData: dco_decode_AnyhowException),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_context_info> cst_encode_box_autoadd_context_info(ContextInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_context_info();
    cst_api_fill_to_wire_context_info(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_32(cst_encode_i_32(raw));
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_i_32_loose> cst_encode_list_prim_i_32_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_i_32_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_i_32_strict> cst_encode_list_prim_i_32_strict(Int32List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_i_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_context_info> cst_encode_opt_box_autoadd_context_info(ContextInfo? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_context_info(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_context_info(ContextInfo apiObj, ffi.Pointer<wire_cst_context_info> wireObj) {
    cst_api_fill_to_wire_context_info(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_context_info(ContextInfo apiObj, wire_cst_context_info wireObj) {
    wireObj.prompt_tokens = cst_encode_i_32(apiObj.promptTokens);
    wireObj.decode_tokens = cst_encode_i_32(apiObj.decodeTokens);
    wireObj.prompt_us = cst_encode_i_64(apiObj.promptUs);
    wireObj.decode_us = cst_encode_i_64(apiObj.decodeUs);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(MnnLlm raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    MnnLlm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Dco(RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_context_info(ContextInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_context_info(ContextInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_context_info(ContextInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
    : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr = _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr.asFunction<void Function(DartPostCObjectFnType)>();

  LlmHandle llm_create(ffi.Pointer<ffi.Char> config_path) {
    return _llm_create(config_path);
  }

  late final _llm_createPtr = _lookup<ffi.NativeFunction<LlmHandle Function(ffi.Pointer<ffi.Char>)>>('llm_create');
  late final _llm_create = _llm_createPtr.asFunction<LlmHandle Function(ffi.Pointer<ffi.Char>)>();

  void llm_destroy(LlmHandle handle) {
    return _llm_destroy(handle);
  }

  late final _llm_destroyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle)>>('llm_destroy');
  late final _llm_destroy = _llm_destroyPtr.asFunction<void Function(LlmHandle)>();

  bool llm_load(LlmHandle handle) {
    return _llm_load(handle);
  }

  late final _llm_loadPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(LlmHandle)>>('llm_load');
  late final _llm_load = _llm_loadPtr.asFunction<bool Function(LlmHandle)>();

  void llm_tune(LlmHandle handle) {
    return _llm_tune(handle);
  }

  late final _llm_tunePtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle)>>('llm_tune');
  late final _llm_tune = _llm_tunePtr.asFunction<void Function(LlmHandle)>();

  void llm_set_config(LlmHandle handle, ffi.Pointer<ffi.Char> config_json) {
    return _llm_set_config(handle, config_json);
  }

  late final _llm_set_configPtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.Pointer<ffi.Char>)>>(
    'llm_set_config',
  );
  late final _llm_set_config = _llm_set_configPtr.asFunction<void Function(LlmHandle, ffi.Pointer<ffi.Char>)>();

  int llm_response_stream(
    LlmHandle handle,
    ffi.Pointer<ffi.Char> prompt,
    LlmStreamCallback cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _llm_response_stream(handle, prompt, cb, user_data);
  }

  late final _llm_response_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UintPtr Function(LlmHandle, ffi.Pointer<ffi.Char>, LlmStreamCallback, ffi.Pointer<ffi.Void>)
        >
      >('llm_response_stream');
  late final _llm_response_stream = _llm_response_streamPtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Char>, LlmStreamCallback, ffi.Pointer<ffi.Void>)>();

  void llm_set_thinking(LlmHandle handle, bool thinking) {
    return _llm_set_thinking(handle, thinking);
  }

  late final _llm_set_thinkingPtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.Bool)>>(
    'llm_set_thinking',
  );
  late final _llm_set_thinking = _llm_set_thinkingPtr.asFunction<void Function(LlmHandle, bool)>();

  void llm_reset(LlmHandle handle) {
    return _llm_reset(handle);
  }

  late final _llm_resetPtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle)>>('llm_reset');
  late final _llm_reset = _llm_resetPtr.asFunction<void Function(LlmHandle)>();

  void llm_generate(LlmHandle handle, int max_tokens) {
    return _llm_generate(handle, max_tokens);
  }

  late final _llm_generatePtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.Int32)>>('llm_generate');
  late final _llm_generate = _llm_generatePtr.asFunction<void Function(LlmHandle, int)>();

  bool llm_stopped(LlmHandle handle) {
    return _llm_stopped(handle);
  }

  late final _llm_stoppedPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(LlmHandle)>>('llm_stopped');
  late final _llm_stopped = _llm_stoppedPtr.asFunction<bool Function(LlmHandle)>();

  bool llm_reuse_kv(LlmHandle handle) {
    return _llm_reuse_kv(handle);
  }

  late final _llm_reuse_kvPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(LlmHandle)>>('llm_reuse_kv');
  late final _llm_reuse_kv = _llm_reuse_kvPtr.asFunction<bool Function(LlmHandle)>();

  ffi.Pointer<ffi.Char> llm_dump_config(LlmHandle handle) {
    return _llm_dump_config(handle);
  }

  late final _llm_dump_configPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(LlmHandle)>>(
    'llm_dump_config',
  );
  late final _llm_dump_config = _llm_dump_configPtr.asFunction<ffi.Pointer<ffi.Char> Function(LlmHandle)>();

  int llm_is_stop(LlmHandle handle, int token) {
    return _llm_is_stop(handle, token);
  }

  late final _llm_is_stopPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(LlmHandle, ffi.Int32)>>('llm_is_stop');
  late final _llm_is_stop = _llm_is_stopPtr.asFunction<int Function(LlmHandle, int)>();

  ffi.Pointer<ffi.Char> llm_tokenizer_decode(LlmHandle handle, int token) {
    return _llm_tokenizer_decode(handle, token);
  }

  late final _llm_tokenizer_decodePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(LlmHandle, ffi.Int32)>>('llm_tokenizer_decode');
  late final _llm_tokenizer_decode = _llm_tokenizer_decodePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(LlmHandle, int)>();

  int llm_tokenizer_encode(
    LlmHandle handle,
    ffi.Pointer<ffi.Char> query,
    ffi.Pointer<ffi.Int32> out_tokens,
    int max_tokens,
  ) {
    return _llm_tokenizer_encode(handle, query, out_tokens, max_tokens);
  }

  late final _llm_tokenizer_encodePtr =
      _lookup<
        ffi.NativeFunction<ffi.UintPtr Function(LlmHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>, ffi.UintPtr)>
      >('llm_tokenizer_encode');
  late final _llm_tokenizer_encode = _llm_tokenizer_encodePtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>, int)>();

  int llm_get_current_history(LlmHandle handle) {
    return _llm_get_current_history(handle);
  }

  late final _llm_get_current_historyPtr = _lookup<ffi.NativeFunction<ffi.UintPtr Function(LlmHandle)>>(
    'llm_get_current_history',
  );
  late final _llm_get_current_history = _llm_get_current_historyPtr.asFunction<int Function(LlmHandle)>();

  void llm_erase_history(LlmHandle handle, int begin, int end) {
    return _llm_erase_history(handle, begin, end);
  }

  late final _llm_erase_historyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.UintPtr, ffi.UintPtr)>>('llm_erase_history');
  late final _llm_erase_history = _llm_erase_historyPtr.asFunction<void Function(LlmHandle, int, int)>();

  void llm_set_kv_cache_info(LlmHandle handle, int add, int remove, ffi.Pointer<ffi.Int32> reserve, int n_reserve) {
    return _llm_set_kv_cache_info(handle, add, remove, reserve, n_reserve);
  }

  late final _llm_set_kv_cache_infoPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.UintPtr, ffi.UintPtr, ffi.Pointer<ffi.Int32>, ffi.Int32)>
      >('llm_set_kv_cache_info');
  late final _llm_set_kv_cache_info = _llm_set_kv_cache_infoPtr
      .asFunction<void Function(LlmHandle, int, int, ffi.Pointer<ffi.Int32>, int)>();

  void llm_generate_init(LlmHandle handle, ffi.Pointer<ffi.Char> end_with) {
    return _llm_generate_init(handle, end_with);
  }

  late final _llm_generate_initPtr = _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.Pointer<ffi.Char>)>>(
    'llm_generate_init',
  );
  late final _llm_generate_init = _llm_generate_initPtr.asFunction<void Function(LlmHandle, ffi.Pointer<ffi.Char>)>();

  int llm_generate_tokens(
    LlmHandle handle,
    ffi.Pointer<ffi.Int32> input_ids,
    int input_len,
    int max_new_tokens,
    ffi.Pointer<ffi.Int32> out_tokens,
    int max_out_tokens,
  ) {
    return _llm_generate_tokens(handle, input_ids, input_len, max_new_tokens, out_tokens, max_out_tokens);
  }

  late final _llm_generate_tokensPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UintPtr Function(
            LlmHandle,
            ffi.Pointer<ffi.Int32>,
            ffi.UintPtr,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.UintPtr,
          )
        >
      >('llm_generate_tokens');
  late final _llm_generate_tokens = _llm_generate_tokensPtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Int32>, int, int, ffi.Pointer<ffi.Int32>, int)>();

  int llm_response_chat(
    LlmHandle handle,
    ffi.Pointer<ffi.Char> chat_json,
    ffi.Pointer<ffi.Char> out_buf,
    int buf_size,
  ) {
    return _llm_response_chat(handle, chat_json, out_buf, buf_size);
  }

  late final _llm_response_chatPtr =
      _lookup<
        ffi.NativeFunction<ffi.UintPtr Function(LlmHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.UintPtr)>
      >('llm_response_chat');
  late final _llm_response_chat = _llm_response_chatPtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  void llm_tune_custom(LlmHandle handle, int tune_type, ffi.Pointer<ffi.Int32> candidates, int num_candidates) {
    return _llm_tune_custom(handle, tune_type, candidates, num_candidates);
  }

  late final _llm_tune_customPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(LlmHandle, ffi.Int32, ffi.Pointer<ffi.Int32>, ffi.UintPtr)>>(
        'llm_tune_custom',
      );
  late final _llm_tune_custom = _llm_tune_customPtr
      .asFunction<void Function(LlmHandle, int, ffi.Pointer<ffi.Int32>, int)>();

  ffi.Pointer<ffi.Char> llm_apply_chat_template(LlmHandle handle, ffi.Pointer<ffi.Char> user_content) {
    return _llm_apply_chat_template(handle, user_content);
  }

  late final _llm_apply_chat_templatePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(LlmHandle, ffi.Pointer<ffi.Char>)>>(
        'llm_apply_chat_template',
      );
  late final _llm_apply_chat_template = _llm_apply_chat_templatePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(LlmHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> llm_apply_chat_template_json(LlmHandle handle, ffi.Pointer<ffi.Char> messages_json) {
    return _llm_apply_chat_template_json(handle, messages_json);
  }

  late final _llm_apply_chat_template_jsonPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(LlmHandle, ffi.Pointer<ffi.Char>)>>(
        'llm_apply_chat_template_json',
      );
  late final _llm_apply_chat_template_json = _llm_apply_chat_template_jsonPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(LlmHandle, ffi.Pointer<ffi.Char>)>();

  void llm_free_string(ffi.Pointer<ffi.Char> str) {
    return _llm_free_string(str);
  }

  late final _llm_free_stringPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
    'llm_free_string',
  );
  late final _llm_free_string = _llm_free_stringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  int llm_get_context_info(LlmHandle handle, ffi.Pointer<ffi.Int> info) {
    return _llm_get_context_info(handle, info);
  }

  late final _llm_get_context_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(LlmHandle, ffi.Pointer<ffi.Int>)>>('llm_get_context_info');
  late final _llm_get_context_info = _llm_get_context_infoPtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Int>)>();

  ffi.Pointer<ffi.Char> llm_get_generated_string(LlmHandle handle) {
    return _llm_get_generated_string(handle);
  }

  late final _llm_get_generated_stringPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(LlmHandle)>>(
    'llm_get_generated_string',
  );
  late final _llm_get_generated_string = _llm_get_generated_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(LlmHandle)>();

  int llm_get_history_tokens(LlmHandle handle, ffi.Pointer<ffi.Int32> out_tokens, int max_tokens) {
    return _llm_get_history_tokens(handle, out_tokens, max_tokens);
  }

  late final _llm_get_history_tokensPtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(LlmHandle, ffi.Pointer<ffi.Int32>, ffi.UintPtr)>>(
        'llm_get_history_tokens',
      );
  late final _llm_get_history_tokens = _llm_get_history_tokensPtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Int32>, int)>();

  int llm_get_output_tokens(LlmHandle handle, ffi.Pointer<ffi.Int32> out_tokens, int max_tokens) {
    return _llm_get_output_tokens(handle, out_tokens, max_tokens);
  }

  late final _llm_get_output_tokensPtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(LlmHandle, ffi.Pointer<ffi.Int32>, ffi.UintPtr)>>(
        'llm_get_output_tokens',
      );
  late final _llm_get_output_tokens = _llm_get_output_tokensPtr
      .asFunction<int Function(LlmHandle, ffi.Pointer<ffi.Int32>, int)>();

  ffi.Pointer<ffi.Char> llm_format_vision_prompt(
    ffi.Pointer<ffi.Char> prompt,
    ffi.Pointer<ffi.Char> image_path,
    int width,
    int height,
  ) {
    return _llm_format_vision_prompt(prompt, image_path, width, height);
  }

  late final _llm_format_vision_promptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int)
        >
      >('llm_format_vision_prompt');
  late final _llm_format_vision_prompt = _llm_format_vision_promptPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int)>();

  ffi.Pointer<ffi.Char> llm_format_vision_multi(
    ffi.Pointer<ffi.Char> prompt,
    ffi.Pointer<ffi.Char> image_paths,
    int width,
    int height,
  ) {
    return _llm_format_vision_multi(prompt, image_paths, width, height);
  }

  late final _llm_format_vision_multiPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int)
        >
      >('llm_format_vision_multi');
  late final _llm_format_vision_multi = _llm_format_vision_multiPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int)>();

  EmbeddingHandle llm_create_embedding(ffi.Pointer<ffi.Char> config_path) {
    return _llm_create_embedding(config_path);
  }

  late final _llm_create_embeddingPtr = _lookup<ffi.NativeFunction<EmbeddingHandle Function(ffi.Pointer<ffi.Char>)>>(
    'llm_create_embedding',
  );
  late final _llm_create_embedding = _llm_create_embeddingPtr
      .asFunction<EmbeddingHandle Function(ffi.Pointer<ffi.Char>)>();

  void llm_destroy_embedding(EmbeddingHandle handle) {
    return _llm_destroy_embedding(handle);
  }

  late final _llm_destroy_embeddingPtr = _lookup<ffi.NativeFunction<ffi.Void Function(EmbeddingHandle)>>(
    'llm_destroy_embedding',
  );
  late final _llm_destroy_embedding = _llm_destroy_embeddingPtr.asFunction<void Function(EmbeddingHandle)>();

  int llm_txt_embedding(
    EmbeddingHandle handle,
    ffi.Pointer<ffi.Char> text,
    ffi.Pointer<ffi.Float> out_buf,
    int buf_size,
  ) {
    return _llm_txt_embedding(handle, text, out_buf, buf_size);
  }

  late final _llm_txt_embeddingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UintPtr Function(EmbeddingHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Float>, ffi.UintPtr)
        >
      >('llm_txt_embedding');
  late final _llm_txt_embedding = _llm_txt_embeddingPtr
      .asFunction<int Function(EmbeddingHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Float>, int)>();

  int llm_ids_embedding(
    EmbeddingHandle handle,
    ffi.Pointer<ffi.Int32> ids,
    int ids_len,
    ffi.Pointer<ffi.Float> out_buf,
    int buf_size,
  ) {
    return _llm_ids_embedding(handle, ids, ids_len, out_buf, buf_size);
  }

  late final _llm_ids_embeddingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UintPtr Function(
            EmbeddingHandle,
            ffi.Pointer<ffi.Int32>,
            ffi.UintPtr,
            ffi.Pointer<ffi.Float>,
            ffi.UintPtr,
          )
        >
      >('llm_ids_embedding');
  late final _llm_ids_embedding = _llm_ids_embeddingPtr
      .asFunction<int Function(EmbeddingHandle, ffi.Pointer<ffi.Int32>, int, ffi.Pointer<ffi.Float>, int)>();

  int llm_embedding_dim(EmbeddingHandle handle) {
    return _llm_embedding_dim(handle);
  }

  late final _llm_embedding_dimPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(EmbeddingHandle)>>(
    'llm_embedding_dim',
  );
  late final _llm_embedding_dim = _llm_embedding_dimPtr.asFunction<int Function(EmbeddingHandle)>();

  double llm_embedding_dist(ffi.Pointer<ffi.Float> vec1, ffi.Pointer<ffi.Float> vec2, int dim) {
    return _llm_embedding_dist(vec1, vec2, dim);
  }

  late final _llm_embedding_distPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>, ffi.UintPtr)>>(
        'llm_embedding_dist',
      );
  late final _llm_embedding_dist = _llm_embedding_distPtr
      .asFunction<double Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>, int)>();

  double llm_embedding_cosine_similarity(ffi.Pointer<ffi.Float> vec1, ffi.Pointer<ffi.Float> vec2, int dim) {
    return _llm_embedding_cosine_similarity(vec1, vec2, dim);
  }

  late final _llm_embedding_cosine_similarityPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>, ffi.UintPtr)>>(
        'llm_embedding_cosine_similarity',
      );
  late final _llm_embedding_cosine_similarity = _llm_embedding_cosine_similarityPtr
      .asFunction<double Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>, int)>();

  void wire__crate__api__MnnLlm_apply_chat_template(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> messages_json,
  ) {
    return _wire__crate__api__MnnLlm_apply_chat_template(port_, that, messages_json);
  }

  late final _wire__crate__api__MnnLlm_apply_chat_templatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_apply_chat_template');
  late final _wire__crate__api__MnnLlm_apply_chat_template = _wire__crate__api__MnnLlm_apply_chat_templatePtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__MnnLlm_chat(int port_, int that, ffi.Pointer<wire_cst_list_prim_u_8_strict> messages_json) {
    return _wire__crate__api__MnnLlm_chat(port_, that, messages_json);
  }

  late final _wire__crate__api__MnnLlm_chatPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_chat');
  late final _wire__crate__api__MnnLlm_chat = _wire__crate__api__MnnLlm_chatPtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  WireSyncRust2DartDco wire__crate__api__MnnLlm_create(ffi.Pointer<wire_cst_list_prim_u_8_strict> config_path) {
    return _wire__crate__api__MnnLlm_create(config_path);
  }

  late final _wire__crate__api__MnnLlm_createPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_create',
      );
  late final _wire__crate__api__MnnLlm_create = _wire__crate__api__MnnLlm_createPtr
      .asFunction<WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__MnnLlm_detokenize(int port_, int that, ffi.Pointer<wire_cst_list_prim_i_32_loose> tokens) {
    return _wire__crate__api__MnnLlm_detokenize(port_, that, tokens);
  }

  late final _wire__crate__api__MnnLlm_detokenizePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_list_prim_i_32_loose>)>
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_detokenize');
  late final _wire__crate__api__MnnLlm_detokenize = _wire__crate__api__MnnLlm_detokenizePtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_cst_list_prim_i_32_loose>)>();

  void wire__crate__api__MnnLlm_dispose(int port_, int that) {
    return _wire__crate__api__MnnLlm_dispose(port_, that);
  }

  late final _wire__crate__api__MnnLlm_disposePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_dispose',
      );
  late final _wire__crate__api__MnnLlm_dispose = _wire__crate__api__MnnLlm_disposePtr
      .asFunction<void Function(int, int)>();

  WireSyncRust2DartDco wire__crate__api__MnnLlm_dump_config(int that) {
    return _wire__crate__api__MnnLlm_dump_config(that);
  }

  late final _wire__crate__api__MnnLlm_dump_configPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_dump_config',
      );
  late final _wire__crate__api__MnnLlm_dump_config = _wire__crate__api__MnnLlm_dump_configPtr
      .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__crate__api__MnnLlm_erase_history(int port_, int that, int begin, int end) {
    return _wire__crate__api__MnnLlm_erase_history(port_, that, begin, end);
  }

  late final _wire__crate__api__MnnLlm_erase_historyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.UintPtr, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_erase_history',
      );
  late final _wire__crate__api__MnnLlm_erase_history = _wire__crate__api__MnnLlm_erase_historyPtr
      .asFunction<void Function(int, int, int, int)>();

  void wire__crate__api__MnnLlm_generate(int port_, int that, ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt) {
    return _wire__crate__api__MnnLlm_generate(port_, that, prompt);
  }

  late final _wire__crate__api__MnnLlm_generatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_generate');
  late final _wire__crate__api__MnnLlm_generate = _wire__crate__api__MnnLlm_generatePtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__MnnLlm_generate_stream(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__MnnLlm_generate_stream(port_, that, prompt, sink);
  }

  late final _wire__crate__api__MnnLlm_generate_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_generate_stream');
  late final _wire__crate__api__MnnLlm_generate_stream = _wire__crate__api__MnnLlm_generate_streamPtr
      .asFunction<
        void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__MnnLlm_get_context_info(int port_, int that) {
    return _wire__crate__api__MnnLlm_get_context_info(port_, that);
  }

  late final _wire__crate__api__MnnLlm_get_context_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_get_context_info',
      );
  late final _wire__crate__api__MnnLlm_get_context_info = _wire__crate__api__MnnLlm_get_context_infoPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_get_generated_string(int port_, int that) {
    return _wire__crate__api__MnnLlm_get_generated_string(port_, that);
  }

  late final _wire__crate__api__MnnLlm_get_generated_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_get_generated_string',
      );
  late final _wire__crate__api__MnnLlm_get_generated_string = _wire__crate__api__MnnLlm_get_generated_stringPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_get_history_length(int port_, int that) {
    return _wire__crate__api__MnnLlm_get_history_length(port_, that);
  }

  late final _wire__crate__api__MnnLlm_get_history_lengthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_get_history_length',
      );
  late final _wire__crate__api__MnnLlm_get_history_length = _wire__crate__api__MnnLlm_get_history_lengthPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_get_history_tokens(int port_, int that) {
    return _wire__crate__api__MnnLlm_get_history_tokens(port_, that);
  }

  late final _wire__crate__api__MnnLlm_get_history_tokensPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_get_history_tokens',
      );
  late final _wire__crate__api__MnnLlm_get_history_tokens = _wire__crate__api__MnnLlm_get_history_tokensPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_get_output_tokens(int port_, int that) {
    return _wire__crate__api__MnnLlm_get_output_tokens(port_, that);
  }

  late final _wire__crate__api__MnnLlm_get_output_tokensPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_get_output_tokens',
      );
  late final _wire__crate__api__MnnLlm_get_output_tokens = _wire__crate__api__MnnLlm_get_output_tokensPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_is_stopped(int port_, int that) {
    return _wire__crate__api__MnnLlm_is_stopped(port_, that);
  }

  late final _wire__crate__api__MnnLlm_is_stoppedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_is_stopped',
      );
  late final _wire__crate__api__MnnLlm_is_stopped = _wire__crate__api__MnnLlm_is_stoppedPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_load(int port_, int that) {
    return _wire__crate__api__MnnLlm_load(port_, that);
  }

  late final _wire__crate__api__MnnLlm_loadPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_llm_flutter_wire__crate__api__MnnLlm_load',
  );
  late final _wire__crate__api__MnnLlm_load = _wire__crate__api__MnnLlm_loadPtr.asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_reset(int port_, int that) {
    return _wire__crate__api__MnnLlm_reset(port_, that);
  }

  late final _wire__crate__api__MnnLlm_resetPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_reset',
      );
  late final _wire__crate__api__MnnLlm_reset = _wire__crate__api__MnnLlm_resetPtr.asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_set_config(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> config_json,
  ) {
    return _wire__crate__api__MnnLlm_set_config(port_, that, config_json);
  }

  late final _wire__crate__api__MnnLlm_set_configPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_set_config');
  late final _wire__crate__api__MnnLlm_set_config = _wire__crate__api__MnnLlm_set_configPtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__MnnLlm_set_thinking(int port_, int that, bool enabled) {
    return _wire__crate__api__MnnLlm_set_thinking(port_, that, enabled);
  }

  late final _wire__crate__api__MnnLlm_set_thinkingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Bool)>>(
        'frbgen_llm_flutter_wire__crate__api__MnnLlm_set_thinking',
      );
  late final _wire__crate__api__MnnLlm_set_thinking = _wire__crate__api__MnnLlm_set_thinkingPtr
      .asFunction<void Function(int, int, bool)>();

  void wire__crate__api__MnnLlm_tokenize(int port_, int that, ffi.Pointer<wire_cst_list_prim_u_8_strict> text) {
    return _wire__crate__api__MnnLlm_tokenize(port_, that, text);
  }

  late final _wire__crate__api__MnnLlm_tokenizePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_tokenize');
  late final _wire__crate__api__MnnLlm_tokenize = _wire__crate__api__MnnLlm_tokenizePtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__MnnLlm_tune(int port_, int that) {
    return _wire__crate__api__MnnLlm_tune(port_, that);
  }

  late final _wire__crate__api__MnnLlm_tunePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_llm_flutter_wire__crate__api__MnnLlm_tune',
  );
  late final _wire__crate__api__MnnLlm_tune = _wire__crate__api__MnnLlm_tunePtr.asFunction<void Function(int, int)>();

  void wire__crate__api__MnnLlm_vision_generate(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> image_paths,
    ffi.Pointer<ffi.Int32> width,
    ffi.Pointer<ffi.Int32> height,
  ) {
    return _wire__crate__api__MnnLlm_vision_generate(port_, that, prompt, image_paths, width, height);
  }

  late final _wire__crate__api__MnnLlm_vision_generatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_vision_generate');
  late final _wire__crate__api__MnnLlm_vision_generate = _wire__crate__api__MnnLlm_vision_generatePtr
      .asFunction<
        void Function(
          int,
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  void wire__crate__api__MnnLlm_vision_generate_stream(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> image_paths,
    ffi.Pointer<ffi.Int32> width,
    ffi.Pointer<ffi.Int32> height,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__MnnLlm_vision_generate_stream(port_, that, prompt, image_paths, width, height, sink);
  }

  late final _wire__crate__api__MnnLlm_vision_generate_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_llm_flutter_wire__crate__api__MnnLlm_vision_generate_stream');
  late final _wire__crate__api__MnnLlm_vision_generate_stream = _wire__crate__api__MnnLlm_vision_generate_streamPtr
      .asFunction<
        void Function(
          int,
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__init_app(int port_) {
    return _wire__crate__api__init_app(port_);
  }

  late final _wire__crate__api__init_appPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_llm_flutter_wire__crate__api__init_app',
  );
  late final _wire__crate__api__init_app = _wire__crate__api__init_appPtr.asFunction<void Function(int)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlmPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_llm_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlmPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlmPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_llm_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlm =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnnLlmPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_context_info> cst_new_box_autoadd_context_info() {
    return _cst_new_box_autoadd_context_info();
  }

  late final _cst_new_box_autoadd_context_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_context_info> Function()>>(
        'frbgen_llm_flutter_cst_new_box_autoadd_context_info',
      );
  late final _cst_new_box_autoadd_context_info = _cst_new_box_autoadd_context_infoPtr
      .asFunction<ffi.Pointer<wire_cst_context_info> Function()>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_i_32(int value) {
    return _cst_new_box_autoadd_i_32(value);
  }

  late final _cst_new_box_autoadd_i_32Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
    'frbgen_llm_flutter_cst_new_box_autoadd_i_32',
  );
  late final _cst_new_box_autoadd_i_32 = _cst_new_box_autoadd_i_32Ptr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_i_32_loose> cst_new_list_prim_i_32_loose(int len) {
    return _cst_new_list_prim_i_32_loose(len);
  }

  late final _cst_new_list_prim_i_32_loosePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_prim_i_32_loose> Function(ffi.Int32)>>(
        'frbgen_llm_flutter_cst_new_list_prim_i_32_loose',
      );
  late final _cst_new_list_prim_i_32_loose = _cst_new_list_prim_i_32_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_i_32_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_i_32_strict> cst_new_list_prim_i_32_strict(int len) {
    return _cst_new_list_prim_i_32_strict(len);
  }

  late final _cst_new_list_prim_i_32_strictPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_prim_i_32_strict> Function(ffi.Int32)>>(
        'frbgen_llm_flutter_cst_new_list_prim_i_32_strict',
      );
  late final _cst_new_list_prim_i_32_strict = _cst_new_list_prim_i_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_i_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(int len) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)>>(
        'frbgen_llm_flutter_cst_new_list_prim_u_8_strict',
      );
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr = _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling = _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_i_32_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_context_info extends ffi.Struct {
  @ffi.Int32()
  external int prompt_tokens;

  @ffi.Int32()
  external int decode_tokens;

  @ffi.Int64()
  external int prompt_us;

  @ffi.Int64()
  external int decode_us;
}

final class wire_cst_list_prim_i_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> ptr;

  @ffi.Int32()
  external int len;
}

typedef LlmHandle = ffi.Pointer<ffi.Void>;
typedef LlmStreamCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(ffi.Pointer<ffi.Char> chunk, ffi.UintPtr len, ffi.Pointer<ffi.Void> user_data)
      >
    >;
typedef EmbeddingHandle = ffi.Pointer<ffi.Void>;
